### ISSUE TITLE
Wireframing

### ISSUE THREAD

**Issue by mikeyboxx** [mikeyboxx/my-daily-almanac#1]

**Comment by ereneedolan** [comment]
https://www.figma.com/file/rnej1yyesHL6M1pDNPmMoc/My-Daily-Almanac?node-id=0%3A1

The link to our wireframe in progress. The far left image is all content on the page but not the layout the user sees. The second iphone screen is reflective of what the user will see with arrows to move through the content boxes while having access to their note taking field/the main body down below. The wireframe to the right is the desktop allowing 4 content boxes to be displayed under the header. Need to build the tablet wireframe which will collapse 4 context boxes to two columns if moving from desktop to tablet/ expand from one column to two if going from a mobile device to tablet.

**Comment by mikeyboxx** [comment]
1. main page (top, middle, bottom)
2. Welcome Dialog box (we collect name, and preferences)
3. Content Dialog Boxes (one per preference)
4. Text-pad data entry dialog box
5. Edit preferences dialog box
6. Text history Dialog box (list of notes represented as date buttons)
