### ISSUE TITLE
Crypto Content box

### ISSUE THREAD

**Issue by mikeyboxx** [mikeyboxx/my-daily-almanac#25]
- [x] create static html page with hardcoded values
- [x] must have 15 crypto coins
- [x] must be displayed in a table
- [x] price must refresh every 3 secs
- [x] must have a javascript function that will accept an object with API data
- [x] must generate a  div container with all html appended to it
- [x] must return the div element
- [x] each container must be same height and width (to be agreed on)

**Comment by ereneedolan** [comment]
Have finished all checkboxes
